M48
; DRILL file {KiCad 8.0.2} date 2024-05-13T11:46:14-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-05-13T11:46:14-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0701
%
G90
G05
T1
X5.2143Y-3.4969
T2
X5.461Y-3.5752
X5.661Y-3.5752
X5.861Y-3.5752
X6.061Y-3.5752
M30
